### ISSUE TITLE
Does uart-rts.dtbo overlay work with RPi4?

### ISSUE THREAD

**Issue by dazz100** [HiassofT/AtariSIO#1]
Hi
I want to enable RTSCTS on RPi3b+ and RPi4.  

I have looked at the latest documentation for Raspbian on my RPi3b+.  It only shows RTSCTS overlays for the new UARTS 2 + on the RPi4.

Have you tested uart-rts.dtbo overlays on RPi4?

Thanks for making these overlays available to people like me.

Dazz

**Comment by HiassofT** [comment]
I just tested on my RPi4 and both uart-rts and uart-ctsrts are working fine.

I noticed a small (mainly cosmetic) issue, the overlays still used the old bcm2708 compatible string. I've changed that to bcm2835 as recommended by latest RPi devicetree guide.

New overlays are pushed, but the old ones should still work fine on RPi4. Please report back if it works for you, too.

**Comment by dazz100** [comment]
Hi
Thanks for that.
I am assuming that uart-rts restores to the default no flow control.  Is that correct?
Dazz

**Comment by HiassofT** [comment]
no, uart-rts only maps RTS on the GPIO header but not CTS.

This is a rather unusual configuration (as you normally need both RTS and CTS for bidirectional handshake) and is only really useful for the very first RPis with 26pin GPIO (where none of the header pins allow mapping of CTS) and very niche applications that don't need CTS.

If you want to use handshake simply load the uart-ctsrts overlay, if you don't want handshake then don't load it and you only have RX and TX on GPIO

**Comment by dazz100** [comment]
Hi
I only need full flow control or none on RPi3-4, so I would not use the uart-rts overlay.
It would be helpful if you could add a document that briefly described what each of your overlays does.
Dazz

**Comment by HiassofT** [comment]
The documentation is in the top-level directory of this project https://github.com/HiassofT/AtariSIO/blob/master/README.RPi and the dts files eg https://github.com/HiassofT/AtariSIO/blob/master/contrib/rpi/miniuart-ctsrts.dts also contain a detailed description what they do

**Comment by dazz100** [comment]
OK.   The Atari title discouraged me from looking there.
Cheers.
