### ISSUE TITLE
atariserver stops with error "cannot get scheduler parameters"

### ISSUE THREAD

**Issue by cstrotm** [HiassofT/AtariSIO#3]
Running Atariserver on 32bit Linux Kernel 5.9.16 the tools stops with error "cannot get scheduler parameters"

**Comment by HiassofT** [comment]
Could you run atariserver with strace and post the output? Would be interesting to know why sched_getparam() fails.

BTW: Which Linux distro are you using and do you have any security manager enabled?

**Comment by HiassofT** [comment]
I've pushed a potential fix (issue a warning instead of doing a hard exit) to the sched branch https://github.com/HiassofT/AtariSIO/tree/sched - could you test if this works?

If you have a LSM installed it might be best to allow atariserver/atarixfer to access the scheduler functions so it can activate realtime scheduling priorities

**Comment by cstrotm** [comment]
> Could you run atariserver with strace and post the output? Would be interesting to know why sched_getparam() fails.

I will run with strace later today and report.

> 
> BTW: Which Linux distro are you using and do you have any security manager enabled?

Void Linux, and there should be no LSM enabled, but I double check.

**Comment by cstrotm** [comment]
> I've pushed a potential fix (issue a warning instead of doing a hard exit) to the sched branch https://github.com/HiassofT/AtariSIO/tree/sched - could you test if this works?

I will test.

As a workaround I've already disabled the hard exit, and atariserver just worked without issues.

**Comment by cstrotm** [comment]
> > Could you run atariserver with strace and post the output? Would be interesting to know why sched_getparam() fails.
> 
> I will run with strace later today and report.
> 
> > BTW: Which Linux distro are you using and do you have any security manager enabled?
> 
> Void Linux, and there should be no LSM enabled, but I double check.

Capabilities and YAMA are active, but no SELinux nor AppArmor:
cat /sys/kernel/security/lsm 
capability,yama

This Void-Linux uses musl-libc instead of glibc, that might be the source of the issue

The strace file is attached
[trace.txt](https://github.com/HiassofT/AtariSIO/files/5793242/trace.txt)

**Comment by cstrotm** [comment]
> > I've pushed a potential fix (issue a warning instead of doing a hard exit) to the sched branch https://github.com/HiassofT/AtariSIO/tree/sched - could you test if this works?
> 
> I will test.
> 
> As a workaround I've already disabled the hard exit, and atariserver just worked without issues.

The 'sched' branch compiles and atariserver starts with the warning. I can't test with an real atari tonight, but I guess it will work, because it is a very similar change that I've already used and that worked for copying around 50 disks.

**Comment by HiassofT** [comment]
Thanks for the info, musl indeed is the culprit. It implements sched_xxx stubs that just return ENOSYS, so no syscalls are performed.

I'll have a look at implementing similar workarounds as util-linux did https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git/commit/schedutils/chrt.c?id=fcc3078754291d2f5121797eb91b364f8e24b2f1 but I'll have to setup a musl dev environment first

**Comment by HiassofT** [comment]
I've pushed a fix to master.

You can now build with `make SCHED_SYSCALLS=1` to get realtime scheduling with musl libc - this will use syscalls instead of libc sched_ functions
