### ISSUE TITLE
Lotharek's 10502PC Sio2PC USB REV2 seems not to require -l anymore

### ISSUE THREAD

**Issue by smesgr9000** [HiassofT/AtariSIO#4]
I have purchased the USB Rev 2 from Lotharek and the file don't seem to require the "-l" option anymore. 
I own an Atari 1050. I'm not sure if my floppy drive would have needed the soldering job but the rev 2 worked out of the box.
If I understand the FAQ @ https://lotharek.pl/productdetail.php?id=157 there was a change to be done to the firmware to change "INVERT RS232 Signals --> RTS# deselected" - I'm not sure what the original issue was but this looks like a firmware fix.

`
$ sudo ./atarixfer -1 -f /dev/ttyUSB0 -dr ~/test2.atr
atarixfer 0.30-210714
(c) 2002-2021 Matthias Reichl <hias@horus.com>
using userspace driver
activated realtime scheduling
mlockall(2) succeeded
get percom block ... failed [atari error 146]
get status ... OK
enhanced density disk
starting to read disk
 1040
successfully created "/home/smesgr/test2.atr" from disk
`
with -l

`
$ sudo ./atarixfer -1 -f /dev/ttyUSB0 -dlr ~/test2.atr
atarixfer 0.30-210714
(c) 2002-2021 Matthias Reichl <hias@horus.com>
using userspace driver
activated realtime scheduling
mlockall(2) succeeded
get percom block ... failed [atari error 138]
get status ... failed [atari error 140]
cannot determine density!
`

could you please update the documentation and maybe atarixfer help option to reflect this.

**Comment by HiassofT** [comment]
Thanks a lot for the heads-up!

I talked with Lotharek about the RTS issue BITD when I implemented support for the device in AtariSIO but wasn't aware that this had been fixed (for a while now) in newer versions.

I'll try to do some tests with my (old) device and update the docs

**Comment by smesgr9000** [comment]
thanks for looking into this

**Comment by HiassofT** [comment]
Sorry for the delay, took me a while to find time to test it and I finally updated the readme and usage-info in atarixfer in the master branch.

Thanks again for reporting the issue!
